
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_test?autoReconnect=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    generate-ddl: true

  logging:
    level:
      me.silvernine: debug
  sql:
    init:
      mode: always

#  Bean error
#  jwt:
#    header: Authorization
#    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#    token-validity-in-seconds: 86400
