
spring:
  mail:
    port: 587
    host: smtp.gmail.com
    username: "hostemail"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true




  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/demo1?autoReconnect=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false

  logging:
    level:
      me.silvernine: debug


  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true
    template-resolver-order: 0

jwt:
  secret: 64yA642V7IaM7ZSE7Yq47Juo7Ja066eI7J207Iqk7YSw6rOgMTExNOyhsOqyve2YhOyKpO2UhOungeu2gO2KuGpzb253ZWJ0b2tlbuuhnOq3uOyduO2ajOybkOqwgOyehQ==
  tokenValidityInseconds: 86400

server:
  servlet:
    encoding:
      charset: UTF-8
